### ISSUE TITLE
What license does this project use? Would like to re-use the cart edge connector.

### ISSUE THREAD

**Issue by darrena092** [soniccd123/Genesis-FeRAM-Cart#1]
Hi there!

Sorry to be a pain, but can you let me know what license you're using for this project? I'm working on a (soon to be) open source Genesis/Megadrive cart, and would like to reuse the cart edge connector component you've made if you would be okay with that. Looks like really great work.

Thanks so much!
Darren

**Comment by soniccd123** [comment]
Hello, I'm still which licence to use, sorry for the inconvenient. Still, don't worrky about the cart edge connector, this part was made by René Richard and its available in his console parts kicad library, licenced with CERN OHL. Here is the repository: https://github.com/db-electronics/kicadlib

**Comment by darrena092** [comment]
Thanks for that!
